### ISSUE TITLE
[Question] Why include version in url?

### ISSUE THREAD

**Issue by Kiefy** [coryleach/UnitySceneSwitcher#7]
Just getting started with UPM, but this is the first time I've seen a version specific url. was curious why you would have people use a url that (if I understand correctly) won't auto-update?

**Comment by coryleach** [comment]
I usually assume users would rather not auto update given that the latest package version may contain breaking changes if say going from a 1.x to a 2.x. If a version is specified they will always get that version and can manually update if they choose and don't end up unexpectedly broken.
